### ISSUE TITLE
Intermittent ranking failures

### ISSUE THREAD

**Issue by kbirk** [uncharted-distil/distil#833]
The MI ranking seems to fail intermittently for me. An example error logged on the server:

```
[ Jan 14 12:54:30 ] [ ERROR ] rpc error: code = Unknown desc = Exception calling application: [Errno 2] No such file or directory: '/home/kbirk/go/src/github.com/unchartedsoftware/distil/datasets/185_baseball/TRAIN/dataset_TRAIN/datasetDoc.json'
```

The `'/home/kbirk/go/src/github.com/unchartedsoftware/distil/datasets/185_baseball/TRAIN/dataset_TRAIN/datasetDoc.json'` file exists:

![image](https://user-images.githubusercontent.com/8975956/51130881-23b87780-17fc-11e9-9b47-61fccf7ef7bf.png)

and directory is mounted as:

```
runner:
  image:
    docker.uncharted.software/distil-pipeline-runner:latest
  ports:
    - "50051:50051"
  environment:
    - D3MOUTPUTDIR=$PWD/outputs
    - VERBOSE_PRIMITIVE_OUTPUT=1
  volumes:
    - $PWD/datasets:/$PWD/datasets
    - $PWD/outputs:/$PWD/outputs
```
